import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Production is a static export (`output: 'export'`), which has no image
      // optimizer for next/image to call, and photos come from Supabase Storage
      // URLs. A plain <img> is the correct element here.
      "@next/next/no-img-element": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage`, which CI runs before lint.
    "coverage/**",
    // The iOS app is a separate Expo project with its own lint setup.
    "mobile/**",
  ]),
]);

export default eslintConfig;
