#!/usr/bin/env node
// Generates src/theme/tokens.generated.ts from the web app's theme tokens in
// ../src/app/globals.css, so the iOS app uses the exact same palette:
// `:root` is dark (the default), `:root[data-theme="light"]` overrides it.
//
//   npm run tokens         regenerate after changing globals.css
//   npm run tokens:check   fail if the generated file is out of date (CI)
//
// Only colour tokens are carried over (hex, rgb[a], hsl[a]); shadows and
// viewport sizes are CSS-only.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const cssPath = join(here, '../../src/app/globals.css');
const outPath = join(here, '../src/theme/tokens.generated.ts');

const COLOR = /^(#[0-9a-f]{3,8}|rgba?\([^)]*\)|hsla?\([^)]*\))$/i;

function block(css, selector) {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`globals.css has no "${selector} {" block`);
  const end = css.indexOf('\n}', start);
  return css.slice(start + selector.length + 2, end);
}

function colorTokens(body) {
  const tokens = {};
  const withoutComments = body.replace(/\/\*[\s\S]*?\*\//g, '');
  for (const decl of withoutComments.split(';')) {
    const match = decl.trim().match(/^--([a-z0-9-]+)\s*:\s*([\s\S]+)$/i);
    if (!match) continue;
    const value = match[2].trim().replace(/\s+/g, ' ');
    if (COLOR.test(value)) tokens[camelCase(match[1])] = value;
  }
  return tokens;
}

function camelCase(name) {
  return name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function render(dark, light) {
  const lines = (tokens) =>
    Object.entries(tokens)
      .map(([k, v]) => `  ${k}: '${v}',`)
      .join('\n');
  return `// Generated by scripts/sync-tokens.mjs from ../src/app/globals.css. Do not edit.
// Run \`npm run tokens\` after changing the web theme.

export const darkTokens = {
${lines(dark)}
} as const;

export const lightTokens: Record<keyof typeof darkTokens, string> = {
${lines(light)}
};

export type ThemeTokens = Record<keyof typeof darkTokens, string>;
`;
}

const css = readFileSync(cssPath, 'utf8');
const dark = colorTokens(block(css, ':root'));
const lightOverrides = colorTokens(block(css, ':root[data-theme="light"]'));

const unknown = Object.keys(lightOverrides).filter((k) => !(k in dark));
if (unknown.length > 0) {
  throw new Error(`Light theme overrides tokens the dark theme lacks: ${unknown.join(', ')}`);
}
const output = render(dark, { ...dark, ...lightOverrides });

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(outPath, 'utf8');
  } catch {
    // Missing counts as stale.
  }
  if (current !== output) {
    console.error('src/theme/tokens.generated.ts is out of date with ../src/app/globals.css. Run `npm run tokens`.');
    process.exit(1);
  }
  console.log(`Theme tokens up to date (${Object.keys(dark).length} colours).`);
} else {
  writeFileSync(outPath, output);
  console.log(`Wrote ${Object.keys(dark).length} colour tokens to src/theme/tokens.generated.ts.`);
}
